# Generated by Django 3.2.8 on 2021-10-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211018_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.CharField(choices=[('Django', 'Django'), ('React Native', 'React Native')], max_length=15),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=7),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Free', 'Free ($0.00)'), ('Standard', 'Standard ($10.00)'), ('Pro', 'Pro ($25.00)')], max_length=20),
        ),
    ]
